name: dbt_bigquery_glamira
version: "1.0.0"
config-version: 2

profile: dbt_bigquery_glamira

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  dbt_bigquery_glamira:

    # STAGING LAYER
    staging:
      +schema: staging
      +materialized: view

    # MART / STAR SCHEMA LAYER
    marts:
      +schema: marts
      +materialized: table
